language: python

python:
  - 2.7

install:
  - pip install -r requirements.txt

script:
#  - python helloworld.py
  - spark-submit abnamro.py 'file:///home/travis/build/manojdalai/Travis/dataset_one.csv'



