language: python

python:
  - 3.7

install:
  - pip install Poetry
  - pip install -r requirements.txt

script:
  #- python -m pytest
  - poetry run pytest tests
#branches:
#  only:
#    - master





#jobs:
#  - include:
#      - stages:
#          - compile
#          - test
#              - script

#- deploy

#script:
#  - python helloworld.py
#  - spark-submit abnamro.py 'input/dataset_one.csv'
#  - poetry run pytest



