language: python

#python:
#  - 3.7

#matrix:
#  include:
#    - name: "Ubuntu 18.04 Bionic"
#      os: linux
#      dist: bionic
#      python:
#        - "3.7"

jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.7

virtualenv:
  system_site_packages: true

before_install:
  - python -m pip install --upgrade pip

install:
  #- pip install Poetry
  - pip install -r requirements.txt
  #- pip install .

script:
  - pytest
  #- python -m pytest
  #- poetry run pytest tests
#branches:
#  only:
#    - master





#jobs:
#  - include:
#      - stages:
#          - compile
#          - test
#              - script

#- deploy

#script:
#  - python helloworld.py
#  - spark-submit abnamro.py 'input/dataset_one.csv'
#  - poetry run pytest



